# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2020-05-20" # 纪念日
CITY: "北京"

BIRTHDAY:
  - "05-21"

APP_ID: "wxf1989994d69e85a6"
APP_SECRET: "696d64f4f8dd462b9de66748c008a524"

USER_ID: 
  - "o2XE562rioPXocQqhD4ZU7rHmwMA"
  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "m6anflATMVmqbXq87_yT3_MSs5KQY58W_QXjI52cgqI"
